GET http://localhost:5000/users
Authorization: bearer 

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Samian Saja",
    "email": "sams@gmail.com",
    "password": "samian",
    "confPassword": "samian",
    "phone_number": 123,
    "img": "art.jpg"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "sams@gmail.com",
    "password": "samian"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout